### ISSUE TITLE
Make init of matomo dynamic with env variables instead of statically typed keys

### ISSUE THREAD

**Issue by AxelEnghamre** [Iteam1337/mandatkollen#21]
just nu är matomo kopplat till matomo.iteam.services/matomo.php med id 3 men för att kunna tracka olika byggen så vore det klokt att flytta dessa värden till en env fil istället

**Comment by irony** [comment]
Smart - ska titta på detta.

**Comment by irony** [comment]
Vi har tagit bort matomo så jag stänger den här.
