### ISSUE TITLE
Date history is not updated when switching polls

### ISSUE THREAD

**Issue by lessp** [Iteam1337/mandatkollen#8]
Hey there, while trying out the code (while on a mission on behalf of Martin) I noticed a minor bug in the source (described below). Let me know if you'd like me to create a PR for this. :-)

### Issue

When clicking the buttons for a specific poll the response does not map to the expected response from the API:

![image](https://user-images.githubusercontent.com/17602389/44350943-e5af6580-a4a0-11e8-8459-b7a4f9e05a29.png)

![image](https://user-images.githubusercontent.com/17602389/44357224-bd7c3280-a4b1-11e8-8b76-ec4f0dc0b055.png)

the history-reducer expects a `date`-property  in the `votes`-object but the property is returned as `dates` from the server.

### Proposal

in `server/app.js` on the `/polls`-route `dates` could be changed to `date` instead:

```js
.then(table => table.map(([institute, M, L, C, KD, S, V, MP, SD, FI, Ö, dates]) => ({institute, dates, parties: {M, L, C, KD, S, V, MP, SD, FI, Ö}})))
```

This should be fine as long as no-one else is dependent on the the API, in which case it would probably be a better idea to change the following line (in `src/reducers/history.js`) to pull the date from `action.votes.dates` instead.

```
return Object.assign(state, { date: action.votes.date })
```

**Comment by irony** [comment]
Perfect Tom! Please issue a PR and I’ll merge it! No one else is using the API so it should be fine!
